/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/sboms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Sbom */
        post: operations["submit_sbom_api_v1_organizations__org_id__sboms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/sboms/{sbom_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sbom */
        get: operations["get_sbom_api_v1_organizations__org_id__sboms__sbom_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_v1_organizations__org_id__cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_api_v1_organizations__org_id__cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_api_v1_organizations__org_id__cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/cases/{case_id}/allowed-transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Allowed Transitions */
        get: operations["allowed_transitions_api_v1_organizations__org_id__cases__case_id__allowed_transitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/cases/{case_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Case */
        post: operations["transition_case_api_v1_organizations__org_id__cases__case_id__transitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/cases/{case_id}/risk-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Risk Decisions */
        get: operations["list_risk_decisions_api_v1_organizations__org_id__cases__case_id__risk_decisions_get"];
        put?: never;
        /** Create Risk Decision */
        post: operations["create_risk_decision_api_v1_organizations__org_id__cases__case_id__risk_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/cases/{case_id}/risk-decisions/{decision_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Risk Decision */
        post: operations["approve_risk_decision_api_v1_organizations__org_id__cases__case_id__risk_decisions__decision_id__approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/cases/{case_id}/verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Verifications */
        get: operations["list_verifications_api_v1_organizations__org_id__cases__case_id__verifications_get"];
        put?: never;
        /** Submit Verification */
        post: operations["submit_verification_api_v1_organizations__org_id__cases__case_id__verifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllowedTransitionsResponse */
        AllowedTransitionsResponse: {
            /** Case Id */
            case_id: string;
            /** Status */
            status: string;
            /** Allowed */
            allowed: string[];
            /** Current */
            current: string;
        };
        /** CaseCreateResponse */
        CaseCreateResponse: {
            /** Id */
            id: string;
            /** Case Key */
            case_key: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Priority */
            priority: string;
            /** Owner Team */
            owner_team: string;
            /** Organization Id */
            organization_id: string;
            /** Version */
            version: number;
            /** Etag */
            etag: string;
            /** Due At */
            due_at?: string | null;
        };
        /** CaseDetailResponse */
        CaseDetailResponse: {
            /** Id */
            id: string;
            /** Case Key */
            case_key: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Priority */
            priority: string;
            /** Owner Team */
            owner_team: string;
            /** Assignee */
            assignee?: string | null;
            /** Organization Id */
            organization_id: string;
            /** Policy Version */
            policy_version?: string | null;
            /** Version */
            version: number;
            /** Etag */
            etag: string;
            /** Due At */
            due_at?: string | null;
            /** Exposures */
            exposures?: string[] | null;
            /** Sla Breached */
            sla_breached: boolean;
            /** Closure Reason */
            closure_reason?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** CaseListResponse */
        CaseListResponse: {
            /** Items */
            items: components["schemas"]["CaseDetailResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ProblemDetails
         * @description Stable error envelope shared by authenticated API operations.
         */
        ProblemDetails: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Fields */
            fields?: string[] | null;
        };
        /** RiskApprovalResponse */
        RiskApprovalResponse: {
            /** Id */
            id: string;
            /** Case Id */
            case_id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Approver */
            approver?: string | null;
            /** Approver Role */
            approver_role?: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Case Status */
            case_status: string;
        };
        /** RiskDecisionCreateResponse */
        RiskDecisionCreateResponse: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Reason */
            reason: string;
            /** Expires At */
            expires_at?: string | null;
            /** Case Status */
            case_status: string;
        };
        /** RiskDecisionResponse */
        RiskDecisionResponse: {
            /** Id */
            id: string;
            /** Case Id */
            case_id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Scope Exposure Ids */
            scope_exposure_ids?: string[] | null;
            /** Reason */
            reason: string;
            /** Compensating Controls */
            compensating_controls?: string[] | null;
            /** Evidence Ids */
            evidence_ids?: string[] | null;
            /** Requested By */
            requested_by: string;
            /** Approver */
            approver?: string | null;
            /** Approver Role */
            approver_role?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** RiskDecisionsResponse */
        RiskDecisionsResponse: {
            /** Items */
            items: components["schemas"]["RiskDecisionResponse"][];
        };
        /** SbomResponse */
        SbomResponse: {
            /** Id */
            id: string;
            /** Organization Id */
            organization_id: string;
            /** Format */
            format: string;
            /** Spec Version */
            spec_version?: string | null;
            /** Content Sha256 */
            content_sha256: string;
            /** Object Uri */
            object_uri: string;
            /** Created At */
            created_at: string;
        };
        /** SbomSubmitResponse */
        SbomSubmitResponse: {
            /** Id */
            id: string;
            /** Sbom Id */
            sbom_id: string;
            /** Submission Id */
            submission_id: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Content Hash */
            content_hash: string;
            /** Digest */
            digest: string;
            /** Status */
            status: string;
            /** Received At */
            received_at: string;
        };
        /** TransitionResponse */
        TransitionResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Version */
            version: number;
            /** Etag */
            etag: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationResponse */
        VerificationResponse: {
            /** Id */
            id: string;
            /** Case Id */
            case_id: string;
            /** Method */
            method: string;
            /** Asserted Result */
            asserted_result?: string | null;
            /** Evidence Ids */
            evidence_ids?: string[] | null;
            /** Coverage */
            coverage?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
        };
        /** VerificationSubmitResponse */
        VerificationSubmitResponse: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Case Status */
            case_status: string;
            /** Coverage */
            coverage?: {
                [key: string]: unknown;
            } | null;
        };
        /** VerificationsResponse */
        VerificationsResponse: {
            /** Items */
            items: components["schemas"]["VerificationResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    submit_sbom_api_v1_organizations__org_id__sboms_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "Content-Type"?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SbomSubmitResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sbom_api_v1_organizations__org_id__sboms__sbom_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                sbom_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SbomResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_api_v1_organizations__org_id__cases_get: {
        parameters: {
            query?: {
                status?: string | null;
                priority?: string | null;
                owner_team?: string | null;
                assignee?: string | null;
                sla_breached?: boolean | null;
                page?: number;
                page_size?: number;
                sort?: string;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseListResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_api_v1_organizations__org_id__cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Title */
                    title: string;
                    /** Owner Team */
                    owner_team: string;
                    /**
                     * Priority
                     * @enum {string}
                     */
                    priority: "P0" | "P1" | "P2" | "P3" | "P4";
                    /** Exposures */
                    exposures?: string[];
                    /** Policy Version */
                    policy_version?: string | null;
                    /** Assignee */
                    assignee?: string | null;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreateResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_api_v1_organizations__org_id__cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    allowed_transitions_api_v1_organizations__org_id__cases__case_id__allowed_transitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowedTransitionsResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_case_api_v1_organizations__org_id__cases__case_id__transitions_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                org_id: string;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Target */
                    target: string;
                    /** Reason */
                    reason?: string | null;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_risk_decisions_api_v1_organizations__org_id__cases__case_id__risk_decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskDecisionsResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_risk_decision_api_v1_organizations__org_id__cases__case_id__risk_decisions_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                org_id: string;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Type
                     * @enum {string}
                     */
                    type: "risk_accepted" | "waiver" | "compensating_control" | "false_positive" | "not_affected";
                    /** Reason */
                    reason: string;
                    /** Scope */
                    scope?: {
                        [key: string]: unknown;
                    } | null;
                    /** Compensating Controls */
                    compensating_controls?: string[] | null;
                    /** Evidence Ids */
                    evidence_ids: string[];
                    /**
                     * Expires At
                     * Format: date-time
                     * @description Timezone-aware timestamp in the future; final future validation is domain-owned.
                     */
                    expires_at: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskDecisionCreateResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_risk_decision_api_v1_organizations__org_id__cases__case_id__risk_decisions__decision_id__approval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                case_id: string;
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Outcome
                     * @enum {string}
                     */
                    outcome: "approve" | "reject";
                    /** Reason */
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskApprovalResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_verifications_api_v1_organizations__org_id__cases__case_id__verifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationsResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_verification_api_v1_organizations__org_id__cases__case_id__verifications_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationSubmitResponse"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Insufficient permission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
