import type { components, operations } from './schema'

// Extract typed response shapes from the generated OpenAPI declarations.
export type CaseDetail = components['schemas']['CaseDetailResponse']
export type CaseCreateResponse = components['schemas']['CaseCreateResponse']
export type CaseListResponse = components['schemas']['CaseListResponse']
export type AllowedTransitionsResponse = components['schemas']['AllowedTransitionsResponse']
export type TransitionResponse = components['schemas']['TransitionResponse']
type TransitionOperation = operations['transition_case_api_v1_organizations__org_id__cases__case_id__transitions_post']
type RiskDecisionOperation = operations['create_risk_decision_api_v1_organizations__org_id__cases__case_id__risk_decisions_post']
type RiskApprovalOperation = operations['approve_risk_decision_api_v1_organizations__org_id__cases__case_id__risk_decisions__decision_id__approval_post']
export type TransitionRequest = NonNullable<TransitionOperation['requestBody']>['content']['application/json']
export type RiskDecisionRequest = NonNullable<RiskDecisionOperation['requestBody']>['content']['application/json']
export type RiskApprovalRequest = NonNullable<RiskApprovalOperation['requestBody']>['content']['application/json']
export type RiskApprovalResponse = components['schemas']['RiskApprovalResponse']
export type RiskDecisionCreateResponse = components['schemas']['RiskDecisionCreateResponse']
export type RiskDecisionItem = components['schemas']['RiskDecisionResponse']
export type RiskDecisionsResponse = components['schemas']['RiskDecisionsResponse']
export type VerificationItem = components['schemas']['VerificationResponse']
export type VerificationSubmitResponse = components['schemas']['VerificationSubmitResponse']
export type VerificationsResponse = components['schemas']['VerificationsResponse']
export type SbomResponse = components['schemas']['SbomResponse']
export type SbomSubmitResponse = components['schemas']['SbomSubmitResponse']
