"""add assets and sbom

Revision ID: 0e36d6c95c1e
Revises: 20f66d1a5a99
Create Date: 2026-09-05 11:30:37.249799

"""

from collections.abc import Sequence

revision: str = "0e36d6c95c1e"
down_revision: str | None = "20f66d1a5a99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
