"""add assets and sbom

Revision ID: 0e36d6c95c1e
Revises: 20f66d1a5a99
Create Date: 2026-09-05 11:30:37.249799

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0e36d6c95c1e'
down_revision: Union[str, None] = '20f66d1a5a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
