"""init provenance

Revision ID: 20f66d1a5a99
Revises: 
Create Date: 2026-09-05 11:24:05.765365

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '20f66d1a5a99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('prior_state', sa.Text(), nullable=True),
    sa.Column('new_state', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_correlation', 'audit_events', ['correlation_id'], unique=False)
    op.create_index('ix_audit_subject', 'audit_events', ['subject_type', 'subject_id'], unique=False)
    op.create_index('ix_audit_time', 'audit_events', ['created_at'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_aggregate', 'outbox_events', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_outbox_correlation', 'outbox_events', ['correlation_id'], unique=False)
    op.create_index('ix_outbox_delivered', 'outbox_events', ['delivered_at'], unique=False)
    op.create_index('ix_outbox_type', 'outbox_events', ['event_type'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=256), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_size', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=64), nullable=True),
    sa.Column('adapter_version', sa.String(length=32), nullable=True),
    sa.Column('object_uri', sa.Text(), nullable=False),
    sa.Column('validation_state', sa.String(length=32), nullable=False),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_record_id', 'content_sha256', name='uq_snapshot_natural_key')
    )
    op.create_index('ix_snapshot_correlation', 'source_snapshots', ['correlation_id'], unique=False)
    op.create_index('ix_snapshot_retrieved', 'source_snapshots', ['retrieved_at'], unique=False)
    op.create_index('ix_snapshot_source', 'source_snapshots', ['source'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_source', table_name='source_snapshots')
    op.drop_index('ix_snapshot_retrieved', table_name='source_snapshots')
    op.drop_index('ix_snapshot_correlation', table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index('ix_outbox_type', table_name='outbox_events')
    op.drop_index('ix_outbox_delivered', table_name='outbox_events')
    op.drop_index('ix_outbox_correlation', table_name='outbox_events')
    op.drop_index('ix_outbox_aggregate', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_audit_time', table_name='audit_events')
    op.drop_index('ix_audit_subject', table_name='audit_events')
    op.drop_index('ix_audit_correlation', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
