"""add intelligence models

Revision ID: b81ddabdfa8e
Revises: 0e36d6c95c1e
Create Date: 2026-09-05 11:32:25.018405

"""

from collections.abc import Sequence

revision: str = "b81ddabdfa8e"
down_revision: str | None = "0e36d6c95c1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
