"""add intelligence models

Revision ID: b81ddabdfa8e
Revises: 0e36d6c95c1e
Create Date: 2026-09-05 11:32:25.018405

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b81ddabdfa8e'
down_revision: Union[str, None] = '0e36d6c95c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
