"""add exposures and risk

Revision ID: caf19df00b97
Revises: b81ddabdfa8e
Create Date: 2026-09-05 11:33:48.277303

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "caf19df00b97"
down_revision: str | None = "b81ddabdfa8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exposures",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=True),
        sa.Column("component_occurrence_id", sa.String(length=64), nullable=True),
        sa.Column("vulnerability_id", sa.String(length=64), nullable=False),
        sa.Column("detection_context", sa.String(length=64), nullable=True),
        sa.Column("match_class", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=True),
        sa.Column("policy_version", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("matched_rules", sa.JSON(), nullable=True),
        sa.Column("evidence_refs", sa.JSON(), nullable=True),
        sa.Column("limitations", sa.JSON(), nullable=True),
        sa.Column("matcher_version", sa.String(length=32), nullable=True),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_exposure_asset", "exposures", ["asset_id"], unique=False)
    op.create_index("ix_exposure_match_class", "exposures", ["match_class"], unique=False)
    op.create_index("ix_exposure_org", "exposures", ["organization_id"], unique=False)
    op.create_index("ix_exposure_priority", "exposures", ["priority"], unique=False)
    op.create_index("ix_exposure_state", "exposures", ["state"], unique=False)
    op.create_index("ix_exposure_vuln", "exposures", ["vulnerability_id"], unique=False)
    op.create_table(
        "match_evidence",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("exposure_id", sa.String(length=64), nullable=False),
        sa.Column("component_purl", sa.Text(), nullable=True),
        sa.Column("vulnerability_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_ref", sa.Text(), nullable=True),
        sa.Column("matcher_version", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["exposure_id"],
            ["exposures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_match_evidence_exposure", "match_evidence", ["exposure_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_match_evidence_exposure", table_name="match_evidence")
    op.drop_table("match_evidence")
    op.drop_index("ix_exposure_vuln", table_name="exposures")
    op.drop_index("ix_exposure_state", table_name="exposures")
    op.drop_index("ix_exposure_priority", table_name="exposures")
    op.drop_index("ix_exposure_org", table_name="exposures")
    op.drop_index("ix_exposure_match_class", table_name="exposures")
    op.drop_index("ix_exposure_asset", table_name="exposures")
    op.drop_table("exposures")
    # ### end Alembic commands ###
