"""create missing asset sbom intel case tables

Revision ID: de6d30ecc5de
Revises: f204c9d671c4
Create Date: 2026-09-05 12:26:51.448726

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "de6d30ecc5de"
down_revision: str | None = "f204c9d671c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("environment", sa.String(length=64), nullable=True),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("criticality", sa.String(length=32), nullable=False),
        sa.Column("data_classification", sa.String(length=32), nullable=True),
        sa.Column("internet_exposure", sa.String(length=32), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("business_service_id", sa.String(length=64), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_asset_org", "assets", ["organization_id"], unique=False)
    op.create_index("ix_asset_status", "assets", ["status"], unique=False)
    op.create_index("ix_asset_type", "assets", ["type"], unique=False)
    op.create_table(
        "components",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purl", sa.Text(), nullable=True),
        sa.Column("ecosystem", sa.String(length=64), nullable=True),
        sa.Column("normalized_name", sa.String(length=512), nullable=True),
        sa.Column("raw_name", sa.String(length=512), nullable=False),
        sa.Column("raw_version", sa.String(length=128), nullable=True),
        sa.Column("cpe", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_component_ecosystem", "components", ["ecosystem"], unique=False)
    op.create_index("ix_component_purl", "components", ["purl"], unique=False)
    op.create_table(
        "remediation_cases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("owner_team", sa.String(length=128), nullable=False),
        sa.Column("assignee", sa.String(length=128), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sla_breached", sa.Boolean(), nullable=False),
        sa.Column("closure_reason", sa.Text(), nullable=True),
        sa.Column("external_ticket_id", sa.String(length=128), nullable=True),
        sa.Column("exposures", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_key"),
    )
    op.create_index("ix_case_due", "remediation_cases", ["due_at"], unique=False)
    op.create_index("ix_case_org", "remediation_cases", ["organization_id"], unique=False)
    op.create_index("ix_case_owner", "remediation_cases", ["owner_team"], unique=False)
    op.create_index("ix_case_priority", "remediation_cases", ["priority"], unique=False)
    op.create_index("ix_case_status", "remediation_cases", ["status"], unique=False)
    op.create_table(
        "sbom_documents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("serial_number", sa.String(length=256), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("spec_version", sa.String(length=32), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("content_size", sa.Integer(), nullable=False),
        sa.Column("object_uri", sa.Text(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("validation_state", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_sha256", "organization_id", name="uq_sbom_digest_org"),
    )
    op.create_index("ix_sbom_org", "sbom_documents", ["organization_id"], unique=False)
    op.create_index("ix_sbom_serial", "sbom_documents", ["serial_number"], unique=False)
    op.create_table(
        "source_statuses",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("freshness", sa.String(length=32), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "scope", name="uq_source_scope"),
    )
    op.create_table(
        "vulnerabilities",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cvss_vector", sa.String(length=256), nullable=True),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("cwe", sa.String(length=64), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_vuln_published", "vulnerabilities", ["published_at"], unique=False)
    op.create_table(
        "advisory_assertions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("vulnerability_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_id", sa.String(length=64), nullable=True),
        sa.Column("content", sa.JSON(), nullable=True),
        sa.Column("kev", sa.Boolean(), nullable=True),
        sa.Column("epss_score", sa.Float(), nullable=True),
        sa.Column("epss_percentile", sa.Float(), nullable=True),
        sa.Column("vex_status", sa.String(length=32), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"],
            ["vulnerabilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_advisory_source", "advisory_assertions", ["source"], unique=False)
    op.create_index("ix_advisory_vuln", "advisory_assertions", ["vulnerability_id"], unique=False)
    op.create_table(
        "affected_ranges",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("vulnerability_id", sa.String(length=64), nullable=False),
        sa.Column("ecosystem", sa.String(length=64), nullable=True),
        sa.Column("purl", sa.Text(), nullable=True),
        sa.Column("introduced", sa.String(length=64), nullable=True),
        sa.Column("fixed", sa.String(length=64), nullable=True),
        sa.Column("last_affected", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"],
            ["vulnerabilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_range_ecosystem", "affected_ranges", ["ecosystem"], unique=False)
    op.create_index("ix_range_vuln", "affected_ranges", ["vulnerability_id"], unique=False)
    op.create_table(
        "asset_aliases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.String(length=64), nullable=False),
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_alias_asset", "asset_aliases", ["asset_id"], unique=False)
    op.create_index(
        "ix_alias_namespace_value", "asset_aliases", ["namespace", "value"], unique=False
    )
    op.create_index("ix_alias_org", "asset_aliases", ["organization_id"], unique=False)
    op.create_table(
        "case_exposures",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("exposure_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["remediation_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_case_exposure_case", "case_exposures", ["case_id"], unique=False)
    op.create_index("ix_case_exposure_exposure", "case_exposures", ["exposure_id"], unique=False)
    op.create_table(
        "component_occurrences",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("sbom_id", sa.String(length=64), nullable=False),
        sa.Column("component_id", sa.String(length=64), nullable=True),
        sa.Column("asset_id", sa.String(length=64), nullable=True),
        sa.Column("purl", sa.Text(), nullable=True),
        sa.Column("ecosystem", sa.String(length=64), nullable=True),
        sa.Column("normalized_name", sa.String(length=512), nullable=True),
        sa.Column("raw_name", sa.String(length=512), nullable=False),
        sa.Column("raw_version", sa.String(length=128), nullable=True),
        sa.Column("cpe", sa.Text(), nullable=True),
        sa.Column("version_scheme", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("evidence_ref", sa.Text(), nullable=True),
        sa.Column("dependency_path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sbom_id"],
            ["sbom_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_occurrence_asset", "component_occurrences", ["asset_id"], unique=False)
    op.create_index(
        "ix_occurrence_component", "component_occurrences", ["component_id"], unique=False
    )
    op.create_index("ix_occurrence_purl", "component_occurrences", ["purl"], unique=False)
    op.create_index("ix_occurrence_sbom", "component_occurrences", ["sbom_id"], unique=False)
    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scope_exposure_ids", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("compensating_controls", sa.JSON(), nullable=True),
        sa.Column("evidence_ids", sa.JSON(), nullable=True),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("approver", sa.String(length=128), nullable=True),
        sa.Column("approver_role", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["remediation_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_risk_case", "risk_decisions", ["case_id"], unique=False)
    op.create_index("ix_risk_expiry", "risk_decisions", ["expires_at"], unique=False)
    op.create_index("ix_risk_status", "risk_decisions", ["status"], unique=False)
    op.create_table(
        "sla_clocks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("breached_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["remediation_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sla_case", "sla_clocks", ["case_id"], unique=False)
    op.create_table(
        "verifications",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("asserted_result", sa.String(length=32), nullable=True),
        sa.Column("evidence_ids", sa.JSON(), nullable=True),
        sa.Column("coverage", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["remediation_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_verif_case", "verifications", ["case_id"], unique=False)
    op.create_table(
        "vulnerability_aliases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("vulnerability_id", sa.String(length=64), nullable=False),
        sa.Column("alias", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["vulnerability_id"],
            ["vulnerabilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vulnerability_id", "alias", name="uq_vuln_alias"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vulnerability_aliases")
    op.drop_index("ix_verif_case", table_name="verifications")
    op.drop_table("verifications")
    op.drop_index("ix_sla_case", table_name="sla_clocks")
    op.drop_table("sla_clocks")
    op.drop_index("ix_risk_status", table_name="risk_decisions")
    op.drop_index("ix_risk_expiry", table_name="risk_decisions")
    op.drop_index("ix_risk_case", table_name="risk_decisions")
    op.drop_table("risk_decisions")
    op.drop_index("ix_occurrence_sbom", table_name="component_occurrences")
    op.drop_index("ix_occurrence_purl", table_name="component_occurrences")
    op.drop_index("ix_occurrence_component", table_name="component_occurrences")
    op.drop_index("ix_occurrence_asset", table_name="component_occurrences")
    op.drop_table("component_occurrences")
    op.drop_index("ix_case_exposure_exposure", table_name="case_exposures")
    op.drop_index("ix_case_exposure_case", table_name="case_exposures")
    op.drop_table("case_exposures")
    op.drop_index("ix_alias_org", table_name="asset_aliases")
    op.drop_index("ix_alias_namespace_value", table_name="asset_aliases")
    op.drop_index("ix_alias_asset", table_name="asset_aliases")
    op.drop_table("asset_aliases")
    op.drop_index("ix_range_vuln", table_name="affected_ranges")
    op.drop_index("ix_range_ecosystem", table_name="affected_ranges")
    op.drop_table("affected_ranges")
    op.drop_index("ix_advisory_vuln", table_name="advisory_assertions")
    op.drop_index("ix_advisory_source", table_name="advisory_assertions")
    op.drop_table("advisory_assertions")
    op.drop_index("ix_vuln_published", table_name="vulnerabilities")
    op.drop_table("vulnerabilities")
    op.drop_table("source_statuses")
    op.drop_index("ix_sbom_serial", table_name="sbom_documents")
    op.drop_index("ix_sbom_org", table_name="sbom_documents")
    op.drop_table("sbom_documents")
    op.drop_index("ix_case_status", table_name="remediation_cases")
    op.drop_index("ix_case_priority", table_name="remediation_cases")
    op.drop_index("ix_case_owner", table_name="remediation_cases")
    op.drop_index("ix_case_org", table_name="remediation_cases")
    op.drop_index("ix_case_due", table_name="remediation_cases")
    op.drop_table("remediation_cases")
    op.drop_index("ix_component_purl", table_name="components")
    op.drop_index("ix_component_ecosystem", table_name="components")
    op.drop_table("components")
    op.drop_index("ix_asset_type", table_name="assets")
    op.drop_index("ix_asset_status", table_name="assets")
    op.drop_index("ix_asset_org", table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
