"""add cases sla verification

Revision ID: f204c9d671c4
Revises: caf19df00b97
Create Date: 2026-09-05 11:41:57.215119

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f204c9d671c4'
down_revision: Union[str, None] = 'caf19df00b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
