"""add actor provenance

Revision ID: f32ac08783d4
Revises: de6d30ecc5de
Create Date: 2026-09-06 16:17:13.995654

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f32ac08783d4"
down_revision: str | None = "de6d30ecc5de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_events",
        sa.Column(
            "actor_provenance",
            sa.String(length=32),
            nullable=False,
            server_default=sa.text("'legacy_request'"),
        ),
    )
    op.add_column(
        "audit_events", sa.Column("actor_principal_type", sa.String(length=16), nullable=True)
    )
    op.add_column("audit_events", sa.Column("actor_roles", sa.JSON(), nullable=True))
    op.add_column("audit_events", sa.Column("actor_scopes", sa.JSON(), nullable=True))
    op.add_column(
        "risk_decisions",
        sa.Column(
            "requested_by_provenance",
            sa.String(length=32),
            nullable=False,
            server_default=sa.text("'legacy_request'"),
        ),
    )
    op.add_column(
        "risk_decisions", sa.Column("approver_provenance", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "risk_decisions", sa.Column("approver_principal_type", sa.String(length=16), nullable=True)
    )
    op.add_column(
        "risk_decisions", sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risk_decisions", "decided_at")
    op.drop_column("risk_decisions", "approver_principal_type")
    op.drop_column("risk_decisions", "approver_provenance")
    op.drop_column("risk_decisions", "requested_by_provenance")
    op.drop_column("audit_events", "actor_scopes")
    op.drop_column("audit_events", "actor_roles")
    op.drop_column("audit_events", "actor_principal_type")
    op.drop_column("audit_events", "actor_provenance")
    # ### end Alembic commands ###
